Portfolio_Proje/Controllers/ExperienceController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Proje.Controllers
{
    public class ExperienceController : Controller
    {
        ExperienceManager experienceManager = new ExperienceManager(new EfExperience());
        public IActionResult Index()
        {
            ViewBag.v1 = "Deneyim Listesi";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Listesi";
            var values = experienceManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddExperience() {

            return View();      
           
        }
        [HttpPost]
        public IActionResult AddExperience(Experience experience)
        {

            experienceManager.TAdd(experience);

            return RedirectToAction("Index");


        }
         public IActionResult DeleteExperience(int id)
        {
           var values=experienceManager.TGetById(id);
            experienceManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditExperience(int id)
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Deneyimler";
            ViewBag.v3 = "Deneyim Düzenleme";
            var values= experienceManager.TGetById(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditExperience(Experience experience)
        {
           
            experienceManager.TUpdate(experience);
            return RedirectToAction("Index");
        }
    }
}

Portfolio_Proje/Views/Experience/AddExperience.cshtml
@model EntityLayer.Concrete.Experience

@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="card-header border-0">
    <h3 class="mb-0">Deneyim Ekleme Sayfası</h3>
</div>
@using (Html.BeginForm("AddExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
                <div class="card">
    <div class="card-body">
        <p class="card-description">Yeni Deneyim Ekle</p>
        <form class="forms-sample">
            <div class="form-group">
                <label for="exampleInputName1">Başlık</label>
                <input type="text" class="form-control" name="ExperienceName">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail3">Deneyim Süresi</label>
                <input type="text" class="form-control" name="ExperienceDate">
            </div> 
            <div class="form-group">
                <label for="exampleInputEmail3">Resim Yolu</label>
                <input type="text" class="form-control" name="ImageUrl" placeholder="Resim Yolu">
            </div>          
    
            <div class="form-group">
                <label for="exampleTextarea1">Açıklama</label>
                <textarea class="form-control" name="Description" rows="4"></textarea>
            </div>
            <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
            <a href="@Url.Action("Index","Experience")" class="btn btn-dark">İptal</a>
        </form>
    </div>
    </div>
    </div>
}

Portfolio_Proje/Views/Experience/EditExperience.cshtml
@model EntityLayer.Concrete.Experience

@{
    ViewData["Title"] = "AddExperience";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}


@using (Html.BeginForm("EditExperience", "Experience", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description">Deneyim Güncelleme</p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label for="exampleInputName1">ID</label>
                        <input type="text" class="form-control" name="ExperienceID" value="@Model.ExperienceID" readonly>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputName1">Başlık</label>
                        <input type="text" class="form-control" name="ExperienceName" value="@Model.ExperienceName">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Deneyim Süresi</label>
                        <input type="text" class="form-control" name="ExperienceDate" value="@Model.ExperienceDate">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Resim Yolu</label>
                        <input type="text" class="form-control" name="ImageUrl" value="@Model.ImageUrl"/>
                    </div>

                    <div class="form-group">
                        <label for="exampleTextarea1">Açıklama</label>
                        <textarea class="form-control" name="Description" rows="4">@Model.Description</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <a href="@Url.Action("Index","Experience")" class="btn btn-dark">İptal</a>
                </form>
            </div>
        </div>
    </div>
}

Portfolio_Proje/Views/Experience/Index.cshtml
@using EntityLayer.Concrete
@model List<Experience>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Deneyimler</h4>
     
            <div class="table-responsive">
                <table class="table">
                    <thead>
                      
                        <tr>
                            <th>#</th>
                            <th>Başlık</th>
                            <th>Tarih</th>
                            <th>Sil</th>
                            <th>Ggüncelle</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.ExperienceID</td>
                                <td>@item.ExperienceName</td>
                                <td>@item.ExperienceDate</td>
                                <td><a href="/Experience/DeleteExperience/@item.ExperienceID" class="btn btn-outline-danger">Sil</a></td>
                                <td><a href="/Experience/EditExperience/@item.ExperienceID"class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }
                        
    
                    </tbody>
                </table>
                <a href="/Experience/AddExperience" class="btn btn-outline-info">Yeni Deneyim Ekle</a>
            </div>
            
        </div>
    </div>
</div>