Portfolio_Proje/Controllers/SkillController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Portfolio_Proje.Controllers
{
    public class SkillController : Controller
    {
        SkillManager skillManager = new SkillManager(new EfSkill());
        public IActionResult Index()
        {
            ViewBag.v1 = "Yetenek Listesi";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Listesi";
            var values = skillManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddSkill()
        {
            ViewBag.v1 = "Yetenek Ekleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Ekleme";
            return View();
        }
        [HttpPost]
        public IActionResult AddSkill(Skill skill)
        {
            skillManager.TAdd(skill);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSkill(int id)
        {
           var values=skillManager.TGetById(id);
            skillManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSkill(int id)
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Yetenekler";
            ViewBag.v3 = "Yetenek Düzenleme";
            var values= skillManager.TGetById(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditSkill(Skill skill)
        {
           
            skillManager.TUpdate(skill);
            return RedirectToAction("Index");
        }
    }
}

Portfolio_Proje/Views/Skill/AddSkill.cshtml
@{
    ViewData["Title"] = "AddSkill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Listesi</h3>
</div>
<form class="form-group" method="post">
    <br/>
    @Html.Label("Yetenek Başlığı")
    <input type="text" name="Title" class="form-control"/>
   <br/>
   <label>Değer</label>
   <input type="text" name="Value" class="form-control"/>
   <br/>
   <button class="btn btn-primary">Kaydet</button>



</form> 

Portfolio_Proje/Views/Skill/EditSkill.cshtml
@model EntityLayer.Concrete.Skill
@{
    ViewData["Title"] = "EditSkill";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Listesi</h3>
</div>
@using (Html.BeginForm("EditSkill", "Skill", FormMethod.Post))
{
     @Html.HiddenFor(x=> x.SkillID)
    <br />
    @Html.Label("Yetenek Başlığı")
    @Html.TextBoxFor(x=> x.Title, new{ @class="form-control"})
    <br />
    <label>Değer</label>
    @Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
}

Portfolio_Proje/Views/Skill/Index.cshtml
@using EntityLayer.Concrete
@model List<Skill>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="card-header border-0">
    <h3 class="mb-0">Yetenek Listesi</h3>
</div>
<table class="table align-items-center table-flush">
    <thead class="thead-light">
        <tr>
            <th scope="col" class="sort" data-sort="name">#</th>
            <th scope="col" class="sort" data-sort="budget">Başlık</th>
            <th scope="col" class="sort" data-sort="status">Oran</th>
            <th scope="col">Sil</th>
            <th scope="col" class="sort" data-sort="completion">Düzenle</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody class="list">
        @foreach (var item in Model)
        {
            <tr>
            <th>@item.SkillID</th>
            <td class="budget">
                @item.Title
            </td>
        
         
            <td>
                <div class="d-flex align-items-center">
                    <span class="completion mr-2">@item.Value%</span>
                    <div>
                        <div class="progress">
                            <div class="progress-bar bg-success " role="progressbar" aria-valuenow="@item.Value" aria-valuemin="0" aria-valuemax="100" style="width: @item.Value%;"></div>
                        </div>
                    </div>
                </div>
            </td>
            <td><a href="/Skill/DeleteSkill/@item.SkillID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Skill/EditSkill/@item.SkillID" class="btn btn-info">Düzenle</a></td>
       
        </tr>
        }
    
    </tbody>
</table>
<a href="/Skill/AddSkill" class="btn btn-primary">Yeni yetenek ekle</a>